### ISSUE TITLE
I want to add  another window when video call is ongoing for seeing my own when video is  ongoing what steps I have to do for that?

### ISSUE THREAD

**Issue by richanshah** [vivek1794/webrtc-android-codelab#43]

**Comment by cannizarro** [comment]
This is already implemented in Step 3 of the codelab. There are two separate videoviews, remote and local.

**Comment by richanshah** [comment]
Hii I am using mqtt with webrtc ,DO u know what needs to be done?I am so
stuck in there

Richa Shah
*Android Developer*
email:  shahricha723@gmail.com

**Comment by cannizarro** [comment]
You are presumably using `MQTT` protocol for signaling (handshaking). I don't have any experience in this protocol but the problem that you are stating about adding the local `videoview` for your own local camera feed will be the same for any implementation of video calling app with `webrtc` it won't depend on the protocol you are using for signaling. I am using `firebase` for signaling and the entire implementation remains the same other than the signaling part.

You only have to change the SignallingClient class to fit your medium for handshaking (exchange of offer and answer), that's it other things remain the same.

If you're going to use the Xirsys turn server just letting you know that the API call to get the Ice servers is asynchronous so you should start the process after there is an API response otherwise the turn servers are never used. I was stuck here for some time.

**Comment by richanshah** [comment]
okay thank you, for now, I am using ice server provided by google but
thanks for the info :)

Richa Shah
*Android Developer* | Smart Sense
email:  shahricha723@gmail.com

**Comment by richanshah** [comment]
Hii Another thing I wanna ask u, I have a video calling app where I also
have taken only one PeerConnection obj and applied custom observer just
like u did ? is it req for me to take two object for streaming on both?
using mqtt
Richa Shah
*Android Developer* | Smart Sense
phone:  9016804343 <09016804343>
email:  shahricha723@gmail.com

**Comment by cannizarro** [comment]
The number of `PeerConnection` objects on a single device serving as a single peer will depend on how many connections it is having with other peers. So if there are n devices connected to a single RTC connection there will be n-1 objects of `PeerConnection` on a single device that is connected to all n of them.
In simpler words, you have to make a new object for every new connection.
**I have never implemented more than a 2-way communication, never needed it. I read the above info somewhere, so please confirm all this before trusting me blindly**, but I am pretty sure about it.
Finally, I'm sorry to have you go through my code, it's a mess :(.

**Comment by richanshah** [comment]
Okay , thank you :) and no problem
Richa Shah
*Android Developer* | Smart Sense
phone:  9016804343 <09016804343>
email:  shahricha723@gmail.com

**Comment by richanshah** [comment]
Hii about using turn server I need more clarification , everything is
working fine for me between android to android using google stun server but
unfortunately it's not working with ios in proper way .it goes to checking
mode.so can u provide me any proper sever details u come across or just
asking tht using turn server its working on all kind devices ?
Richa Shah
*Android Developer* | Smart Sense
email:  shahricha723@gmail.com
